"""add manager in department model

Revision ID: 727fe655f433
Revises: cf9b74ca3684
Create Date: 2024-08-28 09:53:37.366465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727fe655f433'
down_revision: Union[str, None] = 'cf9b74ca3684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'manager_id')
    # ### end Alembic commands ###
