"""fix first name

Revision ID: c484b4e2cf27
Revises: 2246498d217c
Create Date: 2024-08-26 11:03:30.753609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c484b4e2cf27'
down_revision: Union[str, None] = '2246498d217c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=False))
    op.drop_column('user', 'firs_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firs_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
