"""fix dep and pos model

Revision ID: cf9b74ca3684
Revises: 8fbb39948754
Create Date: 2024-08-27 18:55:25.831162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9b74ca3684'
down_revision: Union[str, None] = '8fbb39948754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('positions_name_key', 'positions', type_='unique')
    op.create_unique_constraint('_name_department_', 'positions', ['name', 'department_id'])
    op.create_foreign_key(None, 'positions', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint('_name_department_', 'positions', type_='unique')
    op.create_unique_constraint('positions_name_key', 'positions', ['name'])
    op.drop_column('positions', 'department_id')
    # ### end Alembic commands ###
